# Generated by Django 3.1.2 on 2020-11-25 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201125_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone_numer',
            new_name='phone_number',
        ),
    ]
