# Generated by Django 3.1.2 on 2020-11-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201125_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='home_address',
            field=models.CharField(max_length=120),
        ),
    ]
