# Generated by Django 3.1.2 on 2020-12-14 12:00

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201126_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, default=71234567890, help_text='Contact phone number', max_length=31),
            preserve_default=False,
        ),
    ]
