# Generated by Django 3.1.2 on 2021-01-12 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210104_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.BinaryField(editable=True, null=True),
        ),
    ]
