# Generated by Django 3.1.2 on 2021-01-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210112_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='content_type',
            field=models.CharField(help_text='The MIMEType of the file', max_length=256, null=True),
        ),
    ]
