# Generated by Django 3.1.2 on 2020-11-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
