# Generated by Django 3.1.2 on 2020-11-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_auto_20201116_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='fulldesc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ad',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
