# Generated by Django 3.1.2 on 2020-11-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_auto_20201125_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='text',
            field=models.CharField(max_length=512),
        ),
    ]
