# Generated by Django 3.1.2 on 2020-11-25 07:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_auto_20201125_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='text',
            field=models.CharField(max_length=250, validators=[django.core.validators.MaxLengthValidator(250, 'Description must be less than 250 characters')]),
        ),
    ]
