# Generated by Django 3.1.2 on 2020-11-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('unesco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='area_hectares',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='justification',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='year',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
