# Generated by Django 3.1.2 on 2020-11-08 20:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('unesco', '0002_auto_20201108_2032'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='State',
            new_name='States',
        ),
    ]
